### ISSUE TITLE
Would you please share the pretrained weight?

### ISSUE THREAD

**Issue by miziha-zp** [zr2021/2021_QQ_AIAC_Tack1_1st#1]
thanks for your sharing of your great work. 
In your readme '单模在 1 张 a100 上大约需要 pretrain(2 day)，finetune(2 hour) <br> ', it take much time to produce your work,  Would you please share the pretrained weight for our Further research?

**Comment by zr2021** [comment]
Hi, you can download pretrain weight of job1 here:
https://share.weiyun.com/yUc2W5gw

Load pretrain model here:
https://github.com/zr2021/2021_QQ_AIAC_Tack1_1st/blob/main/job1/finetune.py#L204

**Comment by zr2021** [comment]
Hi, you can download pretrain weight of job1 here:
https://share.weiyun.com/yUc2W5gw

Load pretrained model here:
https://github.com/zr2021/2021_QQ_AIAC_Tack1_1st/blob/main/job1/finetune.py#L204

PengZhang ***@***.***> 于2021年11月7日周日 下午3:09写道：

**Comment by miziha-zp** [comment]
thanks for your sharing. I will close this issue.
