### ISSUE TITLE
why itm task is not used?

### ISSUE THREAD

**Issue by chengmengli06** [zr2021/2021_QQ_AIAC_Tack1_1st#3]
why itm task is not used,heyhey?

**Comment by zr2021** [comment]
hi, **itm** mask is image text matching. (whether frame and title match)
We tried it during the comp, but without success.

**Comment by chengmengli06** [comment]
use the task lead to  a big decrease in accuracy?

**Comment by zr2021** [comment]
> use the task lead to a big decrease in accuracy?

We tried this method: 
Train MLM + MFM + VTC + ITM at the same time: 
(batch1) MLM -> (batch2) MFM -> (batch3) VTC -> (batch4) ITM -> (batch5) MLM -> ...
It lead to a slight decrease.
