### ISSUE TITLE
请问多任务权重如何确定的？

### ISSUE THREAD

**Issue by positivepeng** [zr2021/2021_QQ_AIAC_Tack1_1st#4]
> L = L(tag) * 1250 / 3 + L(mlm) / 3.75 + L(mfm) / 9

您好，我想请问下你们几个权重是如何确定的呢？

**Comment by zr2021** [comment]
> > L = L(tag) * 1250 / 3 + L(mlm) / 3.75 + L(mfm) / 9
> 
> 您好，我想请问下你们几个权重是如何确定的呢？

打印出各任务的梯度，调整权重使各任务梯度量级相近

**Comment by positivepeng** [comment]
好的，谢谢您的回复。
