### ISSUE TITLE
pretrain过程中val_spearman指标先增后降？

### ISSUE THREAD

**Issue by zhouwei5113** [zr2021/2021_QQ_AIAC_Tack1_1st#5]
直接跑job1的pretrain训练代码，发现虽然val_loss一直在下降，但val_spearman是先增后降的，请问可以提供训练log参考下吗？

**Comment by zr2021** [comment]
训练 log 上传到这里了：https://github.com/zr2021/2021_QQ_AIAC_Tack1_1st/blob/main/job1/log/train.log
log 中的 val_spearman 确实是先增后降的，pretrain 阶段的 val_spearman 和 finetune 阶段的 val_spearman 相关性比较弱。

**Comment by zhouwei5113** [comment]
> 训练 log 上传到这里了：https://github.com/zr2021/2021_QQ_AIAC_Tack1_1st/blob/main/job1/log/train.log log 中的 val_spearman 确实是先增后降的，pretrain 阶段的 val_spearman 和 finetune 阶段的 val_spearman 相关性比较弱。

了解了，感谢
