### ISSUE TITLE
calculate_mfm_loss这里算互信息的mask预测特征和原始特征为什么不需要norm？

### ISSUE THREAD

**Issue by zhouwei5113** [zr2021/2021_QQ_AIAC_Tack1_1st#6]
https://github.com/zr2021/2021_QQ_AIAC_Tack1_1st/blob/acd0c35358903addd04a83951d4d74ae3ffcb301/job1/qqmodel/qq_uni_model.py#L110

**Comment by zr2021** [comment]
**不做 normalize** 和 **norm + 温度系数** 实验中效果差不多，就没加 norm。

>https://github.com/zr2021/2021_QQ_AIAC_Tack1_1st/blob/acd0c35358903addd04a83951d4d74ae3ffcb301/job1/qqmodel/qq_uni_model.py#L121
