### ISSUE TITLE
增加音频特征？

### ISSUE THREAD

**Issue by zhouwei5113** [zr2021/2021_QQ_AIAC_Tack1_1st#8]
请教下，如果想继续使用[chinese-roberta-wwm-ext-large](https://huggingface.co/hfl/chinese-roberta-wwm-ext-large)作为预训练模型，如何增加音频模态的特征比较好？

**Comment by zr2021** [comment]
@zhouwei5113 
可以尝试下 [CLS] Text [SEP] Video [SEP] Audio [SEP]，比如下面这篇 paper
https://arxiv.org/pdf/2104.11178.pdf
